### ISSUE TITLE
[PIA-API] Error! Failed to receive Signature!

### ISSUE THREAD

**Issue by notarobot63** [fm407/PIA-NextGen-PortForwarding#13]
Hello,
Thanks for the guide and the awesome documentation.
I have a problem after launching the service: this appears in my logs:
`[PIA-API] Error! Failed to receive Signature!`

Do you have an idea ?

Thanks

**Comment by Hakun1n** [comment]
Hi, 
sorry, @fm407 is not maintaining this repo anymore and i haven't received notification for this. Well I've never faced such issue but it seems like a certificate issue. Which version of pfSense do you have? Also did you tried another PIA server?

**Comment by madeofstown** [comment]
> Hi, sorry, @fm407 is not maintaining this repo anymore and i haven't received notification for this. Well I've never faced such issue but it seems like a certificate issue. Which version of pfSense do you have? Also did you tried another PIA server?

Are planning to update your fork?
