### ISSUE TITLE
Port Forwarding stopped working after update to pfSense 2.5.1

### ISSUE THREAD

**Issue by mikef0** [fm407/PIA-NextGen-PortForwarding#16]
I have been running these scripts for several months without issue on pfSense 2.4.5 and 2.5.0. After updating to 2.5.1, I noticed port forwarding did not seem to be working. I redid all the pfSense related steps to implement the scripts in case something got deleted or broken during the update. 

The log file makes it look as if the scripts are still functioning properly, the pfSense alias for the port is being updated with the new port properly and being updated in transmission as well but when I check to see if the port is open it shows that it is not. 

This is what the log file looks like after restarting my OpenVPN connection,

Jun 9 12:39:03 | root | 56055 | [Trans] New port 32264 successfully updated in remote Transmission system.
-- | -- | -- | --
Jun 9 12:39:03 | root | 54104 | [PIA] New port 32264 updated in pfSense config file.
Jun 9 12:39:03 | check_reload_status | 416 | Reloading filter
Jun 9 12:39:02 | root | 52603 | [PIA] Acquired NEW forwarding port: 32264, current NAT rule port: 37799

Thanks for the help, up until this point the script has been great.

**Comment by pokeimon** [comment]
I believe this is due to this issue introduced in 2.5.1: [Regression #11805](https://redmine.pfsense.org/issues/11805)
I am running the 2.5.2 RC and it fixes the issue.

**Comment by cmer** [comment]
I ran into the same issue with 2.5.1. I upgraded to 2.5.2 RC and still no luck. Did upgrade work for you @mikef0 ?

**Comment by mikef0** [comment]
I just updated to 2.5.2 official release and it appears to be working again.

**Comment by fm407** [comment]
Sorry for the late reply, unfortunately i don't have a pfSense anymore, but if its confirmed to be working again, i will add a warning.
Thanks
