### ISSUE TITLE
xmlstarlet install instructions

### ISSUE THREAD

**Issue by Apsis-IM** [fm407/PIA-NextGen-PortForwarding#17]
including instructions to include freebsd repositories to pkg configuration files and installing xmlstarlet could go a long way.

netgate docs says to edit pfSense.conf
my install has a FreeBSD.conf as well

I edited both.

/usr/local/etc/pkg/repos

FreeBSD: { enabled: yes }

**Comment by Hakun1n** [comment]
Hi,
Thanks for pointing this out.  I've updated the installation details. PR #18 sent.

**Comment by fm407** [comment]
merged, thanks!
