### ISSUE TITLE
Pfsense 2.6.0 (and perhaps PIA VPN in 2022?)

### ISSUE THREAD

**Issue by p4cm4n88** [fm407/PIA-NextGen-PortForwarding#21]
Two things I had to modify in my scripts while taking from this tutorial.

1. 
Line 47 in pia-pfSense.sh

I changed the part that says the following:

get_auth_token () {
  tok=$(curl --interface ${ovpniface} --insecure --silent --show-error --request POST --max-time $curl_max_time \
    --header "Content-Type: application/json" \
    --data "{\"username\":\"$piauser\",\"password\":\"$piapass\"}" \
    "https://www.privateinternetaccess.com/api/client/v2/token" | jq -r '.token')

TO THIS:
get_auth_token () {
  tok=$(curl -s -u $piauser:$piapass --interface $ovpniface --insecure --silent --show-error --max-time 15 "https://privateinternetaccess.com/gtoken/generateToken" | jq -r '.token')
  
  
  In addition, perhaps due to the way I was using PIA? The following modification I had to make to interpret the gateway of the openvpn interface.
  
  on line 96 it reads:
  vpn_ip=$(traceroute -i ${ovpniface} -m 1 privateinternetaccess.com | tail -n 1 | awk '{print $2}')
  
  I modified it to this:
  vpn_ip=$(ifconfig | grep ${ovpniface} -2 | grep "inet 10" | awk '{print $4}')

**Comment by ytinaS** [comment]
Was also having issues getting the script to run on pfsense 2.6.0, the above changes worked for me.

**Comment by fm407** [comment]
this is not maintained anymore.
