### ISSUE TITLE
pfSense 2.7.0

### ISSUE THREAD

**Issue by aspartam1987** [fm407/PIA-NextGen-PortForwarding#22]
Hello everyone,

I had some version mismatch problem with installing the xmlstarlet package on fresh pfSense 2.7.0 setup, so I had to modify the pia-pfSense.sh file to not use this package and also there was not needed to add any other package (jq was installed with the system already).

Actually the solution was replacing:
- Line 39:
`transip=$(xml sel -t -v "//alias[name=\"$ipalias\"]/address" $conffile)`
to:
`transip=$(xmllint --xpath '//alias[name="'$ipalias'"]/address/text()' $conffile)`

- Line 123:
`natport=$(xml sel -t -v "//alias[name=\"$portalias\"]/address" $conffile)`
to:
`natport=$(xmllint --xpath '//alias[name="'$portalias'"]/address/text()' $conffile)`

- Line 138:
`xml ed -u "//alias[name=\"$portalias\"]/address" -v $pf_port $conffile > $tmpconffile`
to:
`cp $conffile $tmpconffile
xmlxml=$(xmllint --shell $tmpconffile << EOF
cd /pfsense/aliases/alias[name="$portalias"]/address
set $pf_port
save
EOF
)`

- Line 144:
`xml val -q $tmpconffile`
to:
`xmlwf -s $tmpconffile`

Now, the code is fully working with pfSense 2.7.0

**Comment by fm407** [comment]
this is not maintained anymore.

**Comment by fm407** [comment]
this is not maintained anymore.

**Comment by fm407** [comment]
this is not maintained anymore.

**Comment by felmey** [comment]
> Now, the code is fully working with pfSense 2.7.0

[aspartam1987](https://github.com/aspartam1987)

I'm trying this with your modifications and I'm getting the following error:

./pia-pfSense.sh: 207: Syntax error: end of file unexpected (expecting "fi")

Any ideas?

**Comment by fm407** [comment]
I don’t maintain this anymore, sorry

**Comment by aspartam1987** [comment]
> > Now, the code is fully working with pfSense 2.7.0
> 
> [aspartam1987](https://github.com/aspartam1987)
> 
> I'm trying this with your modifications and I'm getting the following error:
> 
> ./pia-pfSense.sh: 207: Syntax error: end of file unexpected (expecting "fi")
> 
> Any ideas?

Hi felmey,

my last pfSense was configured more than a year ago...
I started to make an installer script then for the files which can be downloaded from here, with the "patches", but **I don't remember if I have corrected everything or not**. You can find the installer (and check the whole script) here: https://pastebin.com/F06DNSgB

You have to change usernames/passwords on lines 70/71 and 74/75 for sure... AND cross-check the script...
The shared script only installs the scripts/files from this repo with the patches... (if I remember well)
You must follow the excellent README from fm407...

If it is not urgent, I can review the code and steps at the end of January 2025...

**Comment by aspartam1987** [comment]
> > Now, the code is fully working with pfSense 2.7.0
> 
> [aspartam1987](https://github.com/aspartam1987)
> 
> I'm trying this with your modifications and I'm getting the following error:
> 
> ./pia-pfSense.sh: 207: Syntax error: end of file unexpected (expecting "fi")
> 
> Any ideas?

and if you're getting "fi" errors, it means you've added one **if** to the script or you removed one line at the end with **fi** in it...

**Comment by felmey** [comment]
> If it is not urgent, I can review the code and steps at the end of January 2025...

Thanks for the quick response!  No, not urgent...  I was just trying to get it working again.  

Appreciate the help!  I'll check out the pastebin and see if it works on my system.
