### ISSUE TITLE
Dumb question about the service

### ISSUE THREAD

**Issue by Darklyter** [fm407/PIA-NextGen-PortForwarding#4]
I apologize for posting this as an 'issue', but I've been beating my head against the wall.  The script runs great, and I have it set to update Transmission, however I can't for the life of me figure out how to enable the service to run.

Following the instructions I get (or some variation on it):

[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: service pia-portforwarding start
/etc/rc.conf: pia-portforwarding_enable=YES: not found
/etc/rc.conf.local: pia-portforwarding_enable=YES: not found
/etc/rc.conf: pia-portforwarding_enable=YES: not found
/etc/rc.conf.local: pia-portforwarding_enable=YES: not found
/usr/local/etc/rc.d/pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.

or

[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: ./pia-portforwarding start
/etc/rc.conf: pia-portforwarding_enable=YES: not found
/etc/rc.conf.local: pia-portforwarding_enable=YES: not found
./pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.

even though my rc.conf.local is (I've tried one and the other, finally I just got ticked and put both in there):
pia-portforwarding_enable="YES"
pia-portforwarding_enable=YES

So I imagine it's just something I'm missing, not a BSD guy admittedly.  Any suggestions?

**Comment by fm407** [comment]
yes, i will rewrite the service part, that's not the right way to implement it

**Comment by fm407** [comment]
> I apologize for posting this as an 'issue', but I've been beating my head against the wall. The script runs great, and I have it set to update Transmission, however I can't for the life of me figure out how to enable the service to run.
> 
> Following the instructions I get (or some variation on it):
> 
> [2.4.5-RELEASE][[root@homebase.local.lan](mailto:root@homebase.local.lan)]/usr/local/etc/rc.d: service pia-portforwarding start
> /etc/rc.conf: pia-portforwarding_enable=YES: not found
> /etc/rc.conf.local: pia-portforwarding_enable=YES: not found
> /etc/rc.conf: pia-portforwarding_enable=YES: not found
> /etc/rc.conf.local: pia-portforwarding_enable=YES: not found
> /usr/local/etc/rc.d/pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
> Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
> 
> or
> 
> [2.4.5-RELEASE][[root@homebase.local.lan](mailto:root@homebase.local.lan)]/usr/local/etc/rc.d: ./pia-portforwarding start
> /etc/rc.conf: pia-portforwarding_enable=YES: not found
> /etc/rc.conf.local: pia-portforwarding_enable=YES: not found
> ./pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
> Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
> 
> even though my rc.conf.local is (I've tried one and the other, finally I just got ticked and put both in there):
> pia-portforwarding_enable="YES"
> pia-portforwarding_enable=YES
> 
> So I imagine it's just something I'm missing, not a BSD guy admittedly. Any suggestions?

Could you try this please:

```
#!/bin/sh

. /etc/rc.subr

name="pia-portforwarding"
rcvar="pia-portforwarding_enable"
command="/home/custom/piaportforward/pia-pfSense.sh"
pidfile="/var/run/pia-portforwarding.pid"

load_rc_config $name
: ${pia-portforwarding_enable:=yes}

start_cmd="/usr/sbin/daemon -p $pidfile -P /var/run/pia-portforwarding-daemon.pid $command >> /var/log/pia-portforwarding 2>&1"

run_rc_command "$1"
```

**Comment by Darklyter** [comment]
Nope, same sort of error.  Took out the entry from rc.conf.local before I captured this, but you're just missing that same line (Tried running directly and as a service):

[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: ./pia-portforwarding start
./pia-portforwarding: OVIDE:: not found
./pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: service pia-portforwarding start
/usr/local/etc/rc.d/pia-portforwarding: OVIDE:: not found
/usr/local/etc/rc.d/pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d:

**Comment by fm407** [comment]
can you paste your /etc/rc.conf

**Comment by Darklyter** [comment]
Sorry, I'm an idiot.  Didn't see that my paste started halfway into "PROVIDE".  Still getting the error though, just without the annoying OVIDE:: line.  Sheesh.

[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: ./pia-portforwarding
Usage: ./pia-portforwarding [fast|force|one|quiet](start|stop|restart|rcvar|enabled|describe|extracommands|status|poll)
[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: service pia-portforwarding start
/usr/local/etc/rc.d/pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d:

**Comment by Darklyter** [comment]
Well, rc.conf.local since pfSense ignores rc.conf.  Just one line:
pia-portforwarding_enable="YES"

but what I posted a second ago was with no entries at all, then I just tried it with and without quotes.  Just gives me the extra "not found" line if there's something in there.

[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: ./pia-portforwarding start
/etc/rc.conf.local: pia-portforwarding_enable=YES: not found
./pia-portforwarding: WARNING: $pia-portforwarding_enable is not set properly - see rc.conf(5).
Cannot 'start' pia-portforwarding. Set pia-portforwarding_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.
[2.4.5-RELEASE][root@homebase.local.lan]/

PS. Probably should have pasted in the time I tried it with quotes since that's how it's supposed to be.  So this edit is doing that

**Comment by fm407** [comment]
nano /etc/rc.conf.local and paste pia-portforwarding_enable="YES", pfSense overwrites /etc/rc.conf but leaves alone /etc/rc.conf.local

**Comment by Darklyter** [comment]
Right, that's what I have in there.  (The reason for the previous edit was because I was trying it empty, with quote and without quotes three different times.  I copied and pasted the wrong line entry)

[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d: cat /etc/rc.conf.local
pia-portforwarding_enable="YES"
[2.4.5-RELEASE][root@homebase.local.lan]/usr/local/etc/rc.d:

Edit: in case of typo I just pasted yours and tried again, no difference.

**Comment by fm407** [comment]
okay i think i got it, its not liking the - in the filename try with this:

```
#!/bin/sh

. /etc/rc.subr

name="piaportforwarding"
rcvar="piaportforwarding_enable"
command="/home/custom/piaportforward/pia-pfSense.sh"
pidfile="/var/run/piaportforwarding.pid"

load_rc_config $name

start_cmd="/usr/sbin/daemon -p $pidfile -P /var/run/piaportforwarding-daemon.pid $command >> /var/log/piaportforwarding 2>&1"

run_rc_command "$1"
```
and in rc.conf.local: piaportforwarding_enable="YES"

```
touch /usr/local/etc/rc.d/piaportforwarding
chmod +x /usr/local/etc/rc.d/piaportforwarding
vi /usr/local/etc/rc.d/piaportforwarding
```

**Comment by Darklyter** [comment]
Definitely closer.  That lets it run, but it doesn't stay running.  (I also changed /usr/local/etc/devd/piaport.conf, couldn't think of anything else that needed it)

[2.4.5-RELEASE][root@homebase.local.lan]/root: service piaportforwarding status
piaportforwarding is not running.
[2.4.5-RELEASE][root@homebase.local.lan]/root: service piaportforwarding start
[2.4.5-RELEASE][root@homebase.local.lan]/root: service piaportforwarding status
piaportforwarding is not running.
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux |grep pia
root     1216   0.0  0.0  6560  2324  0  S+   22:17   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root:

**Comment by Darklyter** [comment]
Ok, so after a reboot it seemed to run correctly, but then immediately went away and the process closed out.  I'm not sure of the Daemon command, so it might just trigger every xx minutes, but if it's supposed to stay resident it's not.  (Also don't forget about updating /usr/local/etc/devd/piaport.conf as well)

[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux |grep pia
root    43905   0.0  0.0  6976  2472  -  S    22:21   0:00.00 /bin/sh /home/custom/piaportforward/pia-pfSense.sh
root    49197   0.0  0.0  6292  1972  -  Ss   22:21   0:00.00 daemon: /home/custom/piaportforward/pia-pfSense.sh[49232] (daemon)
root    49232   0.0  0.0  6976  2472  -  S    22:21   0:00.00 /bin/sh /home/custom/piaportforward/pia-pfSense.sh
root    44525   0.0  0.0  6560  2324  0  S+   22:21   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    52490   0.0  0.0  6560  2324  0  S+   22:21   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    85381   0.0  0.0  6560  2324  0  S+   22:21   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    85735   0.0  0.0  6560  2324  0  S+   22:21   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    86091   0.0  0.0  6560  2324  0  S+   22:21   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    86676   0.0  0.0  6560  2324  0  S+   22:21   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    90949   0.0  0.0  6560  2324  0  S+   22:22   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: service piaportforwarding status
piaportforwarding is not running.
[2.4.5-RELEASE][root@homebase.local.lan]/root: service piaportforwarding start
[2.4.5-RELEASE][root@homebase.local.lan]/root: service piaportforwarding status
piaportforwarding is not running.
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    92752   0.0  0.0  6292  1972  -  Ss   22:22   0:00.00 daemon: /home/custom/piaportforward/pia-pfSense.sh[92863] (daemon)
root    92863   0.0  0.0  6976  2704  -  S    22:22   0:00.00 /bin/sh /home/custom/piaportforward/pia-pfSense.sh
root    94633   0.0  0.0  6560  2324  0  S+   22:22   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    92752   0.0  0.0  6292  1972  -  Ss   22:22   0:00.00 daemon: /home/custom/piaportforward/pia-pfSense.sh[92863] (daemon)
root    92863   0.0  0.0  6976  2712  -  S    22:22   0:00.00 /bin/sh /home/custom/piaportforward/pia-pfSense.sh
root    94951   0.0  0.0  6976  2712  -  S    22:22   0:00.00 /bin/sh /home/custom/piaportforward/pia-pfSense.sh
root    95774   0.0  0.0  6560  2252  0  R+   22:22   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    39181   0.0  0.0  6560  2324  0  S+   22:22   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ps aux | grep pia
root    52409   0.0  0.0  6560  2324  0  S+   22:22   0:00.00 grep pia
[2.4.5-RELEASE][root@homebase.local.lan]/root: ls -l /var/run/pia*
ls: No match.
[2.4.5-RELEASE][root@homebase.local.lan]/root:

PS. Sorry for hitting you up with all of the pasting, but thanks for taking a look and helping out.  Greatly appreciate all of this, especially you doing it in the first place!

**Comment by fm407** [comment]
this works on my test box:

```
#!/bin/sh

# REQUIRE: LOGIN

. /etc/rc.subr

name="piaportforwarding"
rcvar="${name}_enable"
command="/home/custom/piaportforward/pia-pfSense.sh"
command_interpreter="/usr/local/bin/bash"
pf_user=root
start_cmd="/usr/sbin/daemon -u $pf_user $command"

load_rc_config $name
run_rc_command "$1"
```

and in rc.conf.local piaportforwarding_enable="YES"

also the script in devd is what starts and stops the service when the interface goes up/down, its quite important, you just need to update the name of the service:

```
notify 0 {
        match "system"          "IFNET";
        match "subsystem"       "(ovpnc1)";
        match "type"            "LINK_UP";
        action "logger $subsystem is UP";
        action "service piaportforwarding start";
};

notify 0 {
        match "system"          "IFNET";
        match "subsystem"       "(ovpnc1)";
        match "type"            "LINK_DOWN";
        action "logger $subsystem is DOWN";
        action "service piaportforwarding stop";
};
```

**Comment by Darklyter** [comment]
Ok, I figured out what was going on...  in my testing my changes broke the Transmission update, and I didn't realize it had a forced exit() on there.  Fixing the 'interface' let it start working correctly.  Thank you so much!

(Though I did change the line to  command_interpreter="/bin/sh" since I don't have bash in my /usr/local/bin)

Thanks again!

**Comment by fm407** [comment]
glad it works, ill make the changes in the main documentation and close the issue, thanks!

**Comment by Darklyter** [comment]
Thank you sir!  You're a rockstar!  :-)
